version: "3.7"

services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    ports:
      - "27017:27017"


