version: "3.7"

services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    ports:
      - "27017:27017"
    networks:
      - demo

  redis:
    image: redis:6.0
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    networks:
      - demo

  prometheus:
    image: prom/prometheus:v2.27.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
    network_mode: "host"

  grafana:
    image: grafana/grafana:7.5.6
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    network_mode: "host"
networks:
  demo:
    driver: bridge
